server:
  port: 8081
spring:
  # MYSQL
  datasource:
    # 数据库连接
    url: jdbc:mysql://106.12.23.30:3306/spike
    # 数据库用户
    username: root
    # 数据库密码
    password: 970205
    # 数据库驱动名
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 106.12.23.30
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000

  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

# mybatis
mybatis:
  type-aliases-package: com.xjm.spike.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/xjm/spike/dao/*.xml